### ISSUE TITLE
500 error after 5.3.2 workshop update

### ISSUE THREAD

**Issue by rayhatfield** [epicweb-dev/react-suspense#92]
After pulling the latest update react-suspense workshop I get a 500 error when hitting `http://localhost:5639/`.

I've done a fresh clone and `npm run setup` without errors and still see the 500.

```sh
✅  Workshop setup complete...

react-suspense on  main took 11s ⟩npm start

> start
> npx --prefix ./epicshop epicshop start

🐨  Let's get learning!
Local:            http://localhost:5639
On Your Network:  http://192.168.86.58:5639
Press Ctrl+C to stop
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      "discordProfile",
      "nick"
    ],
    "message": "Expected string, received null"
  }
]
    at Object.get error [as error] (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/zod/lib/index.mjs:587:31)
    at ZodEffects.parse (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/zod/lib/index.mjs:692:22)
    at getFreshValue (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/workshop-app/app/utils/epic-api.ts:638:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getFreshValue (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/cachified/src/getFreshValue.ts:17:24)
    at Module.cachified (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/cachified/src/cachified.ts:89:17)
    at file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/remix-utils/build/common/promise.js:30:106
    at async Promise.all (index 3)
    at promiseHash (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/remix-utils/build/common/promise.js:30:31)
    at loader$y (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/workshop-app/app/root.tsx:106:21) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ]
}
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      "discordProfile",
      "nick"
    ],
    "message": "Expected string, received null"
  }
]
    at Object.get error [as error] (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/zod/lib/index.mjs:587:31)
    at ZodEffects.parse (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/zod/lib/index.mjs:692:22)
    at getFreshValue (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/workshop-app/app/utils/epic-api.ts:638:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getFreshValue (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/cachified/src/getFreshValue.ts:17:24)
    at Module.cachified (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/cachified/src/cachified.ts:89:17)
    at file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/remix-utils/build/common/promise.js:30:106
    at async Promise.all (index 3)
    at promiseHash (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/remix-utils/build/common/promise.js:30:31)
    at loader$y (file:///Users/ray/projects/learn/react-suspense/epicshop/node_modules/@epic-web/workshop-app/app/root.tsx:106:21) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ]
}
```

![2024-10-08 at 14 40 41@2x](https://github.com/user-attachments/assets/4a5393ac-bb82-409b-98ea-abc46a69f854)

If I switch to the [last commit from yesterday](https://github.com/epicweb-dev/react-suspense/commit/10185b4cfd65e4fc7877a0fd9ee195b47c2ce7f2) it works again.

**Comment by kentcdodds** [comment]
So sorry about this! It should be fixed now!
